class MainMenu:
    def __init__(self, font_header): ...

    def get_main_menu(self): ...

    def go_to_main_menu(self): ...

    def go_to_calculator(self): ...

    def go_to_numerical_system(self): ...

    def go_to_numerical_system_arithmetic(self): ...

    def go_to_graphics(self): ...

    def go_to_derivative(self): ...


class FontRegistry:

    def __init__(self): ...

    def get_font_header(self): ...

    def get_font_calculator(self): ...

    def get_font_common(self): ...

    def get_font_axis(self): ...

    def get_font_num_sys_arith(self): ...


class Themes:

    def __init__(self): ...

    def get_global_theme(self): ...

    def get_disabled_theme(self): ...

    def get_shifted_theme(self): ...

    def get_default_button_theme(self): ...

    def get_disabled_button_theme(self): ...
